### ISSUE TITLE
[Important] Work checklist

### ISSUE THREAD

**Issue by ikarago** [UnigramDev/Unigram#4]
_Last Updated: 22-08-2016 13:30 CEST_
These are the lists to keep track of the tasks that we have to do.

If you wish to work on a task, leave a comment below, Once assigned your name will be placed behind the task. For more details on a task, check the individual issues with the same name. If you take on a task and an (detailed) Issue has not yet been made, please feel free to add one and fill in the details.

**Code:**
- [x] Prepare main project files in master for developmentbranch (@guerrerotook)
- [x] Make communication with the Telegram API possible (@guerrerotook & @wileymarques)
- [x] Build back end (@FrayxRulez)
- [ ] Build chat page and make it functional (basic chats) (@FrayxRulez)
- [x] Build background tasks (@FrayxRulez)
- [ ] Start simple chats in the views
- [x] Add Live Tile & Toast Notifications (@FrayxRulez)
- [x] Build Basic Cortana-commands (@ikarago)
- [ ] Make Unigram a Share-target for text and images. (@ikarago)
- [ ] Integrate with People Hub
- [ ] Add more features
- [ ] Drink tea/coffee

**Design:**
- [x] Make designs for every page in the app (@gxsaurav)
- [ ] Build XAML-mockups of the designs (@ikarago & @JuanPZV)
- [ ] Make XAML-pages functional
- [ ] Make XAML-pages accessible with the Xbox-controller (@ikarago)
- [ ] Design more features
- [x] Drink tea/coffee (@everyone)

**Comment by AlexanderSilvaB** [comment]
Hi, I learned of this project through the WindowsClub.com.br and I am very interested. I am the developer of Notiny and want to help in whatever it takes to make it happen! :)

**Comment by wileymarques** [comment]
I will help on making communication to the API!

**Comment by danielsteiner** [comment]
Don't forget to add "Drink Red Bull" and "eat Pizza"

**Comment by DarthJahus** [comment]
@danielsteiner, is Red Bull OpenSource? It would be hard to use it with the current licence 😏

**Comment by robertiagar** [comment]
Hello everyone! I'd like to chip in and help built this app. Do I need to be added as a collaborator or should I fork the app and go the traditional way and create pull requests for adding features?

**Comment by FrayxRulez** [comment]
Hi @robertiagar! Actually we prefer fork and pull for now :smile:

**Comment by BadCode7** [comment]
Drink Coffee 😃

**Comment by d8vjork** [comment]
Translate, maybe need translators :+1:

**Comment by ikarago** [comment]
We'll be waiting a bit with the translations until we've got most of the features down. After that, we'll welcome all the translations! :)

**Comment by FrayxRulez** [comment]
I'm going to close this issue, and I've already started to create [projects](https://github.com/UnigramDev/Unigram/projects) to replace it

**Comment by DarthJahus** [comment]
I suggest adding 2FA integration as a priority.

Two months ago, I disabled 2FA to test an alpha build of Unigram. At that time, the government accessed my account by intercepting the SMS code. Fortunately, though, I was online, disconnected them and have set 2FA. This should be a warning to everyone.

**Comment by FrayxRulez** [comment]
Hey, can you create a new issue instead of using this one? Thank you
